apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-python
  labels:
    app: usermanagement-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermanagement-python
  template:
    metadata:
      labels:
        app: usermanagement-python
    spec:
      containers:
        - name: usermanagement-python
          image: bayeracr.azurecr.io/bayer-usermagement

          ports:
            - containerPort: 8000  # Adjust based on your app's listening port        
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-python-service
spec:
  type: LoadBalancer
  selector:
    app: usermanagement-python
  ports:
    - port: 8000
      targetPort: 8000
